### ISSUE TITLE
Suggestions for simulator.c

### ISSUE THREAD

**Issue by pb-cdunn** [thegenemyers/DAZZ_DB#15]
I'd like to sample from a real reference genome, and these changes would help.

1. Make `random_genome()` a separate program.
2. Read reference GENOME from file.
  * It does not need to be a real fasta. Just a single line of letters would be enough.
3. Allow circular-sampling.
  * This might not be physically realistic, but it's an easy change.

**Comment by pb-cdunn** [comment]
Your new simulator.c looks good.

Curiosity: Why do you add 1 to the read# in DBdump, LAshow, and LAdump? Historical reasons?

**Comment by pb-cdunn** [comment]
And one other thing: I *really* need to control the `FLIP` rate. Forward-only subreads are invaluable in analyzing Falcon.

**Comment by thegenemyers** [comment]
Just decided start counting from 1.  While C has 0-based indexing must
people are confused by this.  The convention for intervals isn't about where
you start counting, its about the fact that intervals spanning things 
are best
about using the marks between the things.
    -- Gene

**Comment by pb-cdunn** [comment]
I tested your change for FLIP (sent via email). Works for me. Many thanks, as usual.
