### ISSUE TITLE
Non-interactive DBsplit

### ISSUE THREAD

**Issue by pb-cdunn** [thegenemyers/DAZZ_DB#20]
```sh
+ DBsplit -x250 -s500 -a rawreads
You are about to overwrite the current partition settings.  This
will invalidate any tracks, overlaps, and other derivative files.
Are you sure you want to proceed? [Y/N]
```
That's a problem when it happens within a script. It's important to be able to re-use `.bps` and `.idx`, since recreating that from 300GB of gzipped fasta takes `30-40mins`. In our workflow, on a restart we delete all the tracks, etc. and re-split if parameters have changed.

I guess `DBsplit` needs a non-interactive flag. Maybe `-f` for "force"?

**Comment by thegenemyers** [comment]
The requested -f flag will be in the next update.  Cheers, Gene

**Comment by pb-cdunn** [comment]
Thanks, Gene!
