### ISSUE TITLE
Catrack fails to compile

### ISSUE THREAD

**Issue by gt1** [thegenemyers/DAZZ_DB#25]
Compiler messages:

gcc -O3 -Wall -Wextra -Wno-unused-result -fno-strict-aliasing -o Catrack Catrack.c DB.c QV.c -lm
Catrack.c: In function ‘main’:
Catrack.c:110:13: error: ‘nfile’ undeclared (first use in this function)
         if (nfile > 0)
             ^
Catrack.c:110:13: note: each undeclared identifier is reported only once for each function it appears in

I guess nfile should be nfiles in line 110.

**Comment by thegenemyers** [comment]
Yes, fixed it, no idea how it got past me given it is a compile time error.
    -- Gene
