### ISSUE TITLE
Random Access of DAZZ_DB causes long I/O wait

### ISSUE THREAD

**Issue by pb-cdunn** [thegenemyers/DAZZ_DB#27]
Herr Myers,

We use the DAZZLER database for our consensus tools. On some filesystems, the bottleneck is the random-access of the DAZZ_DB records. (I don't think the `.las` files cause a problem since we only scan them sequentially.) David Gordon worked around this problem by copying the DB into [ram-disk](https://www.cyberciti.biz/tips/what-is-devshm-and-its-practical-usage.html), which is fine if you have sufficient memory.

We are thinking of writing some code to memoize access to the DB records. I was hoping to learn your thoughts on the matter.

Mfg, Chris

**Comment by thegenemyers** [comment]
As you know, memoization will only help if a given "job" if the 
distribution of read requests
is concentrated on a subset of the total.  A way to get that after the 
daligner phase would be
to compute a tentative contig path (it does not need to be correct), 
that walks through the
reads in order of their "overlap" along the genome.  This would 
guarantee the concentration
required during the scrubbing and correction phases.  Later for the 
consensus Arrow phase
one could use the actual assembly to order the reads.  This resorting 
could be accomplished
in a two-stage, external split and merge setup (I think).

    Alternatively, the memory for 2-bit encoded 100X human genome data 
set is 75Gb.  With a
128Gb memory available on most machines, I would simply load up the 
compressed DB and
do the decompress on the fly as sequences are needed.

    Cheers,
        Gene

**Comment by pb-cdunn** [comment]
Those are interesting ideas for working on concentrated subsets of reads. But we may not ever need that.

>  Alternatively, the memory for 2-bit encoded 100X human genome data set is 75Gb. With a 128Gb memory available on most machines, I would simply load up the compressed DB and do the decompress on the fly as sequences are needed.

Ok. Thanks. We have that working now in LA4Falcon, which feeds reads/alignments to the corrections phase.
