### ISSUE TITLE
DB2fasta warning

### ISSUE THREAD

**Issue by ebioman** [thegenemyers/DAZZ_DB#28]
Hello
I wanted to try the scrubbing module today and followed the modulated pipeline till DASedit.
Afterwards, I wanted to get my reads out of the database to compare them with different assemblers which I tried with:

    DB2fasta -v scrubbed_reads.db
    Creating 000000F.ALLV31.subreads.fasta ...
    DB2fasta: Index out of bounds (Load_Read)

The file is generated though with 1.8GB and 150052 reads from 150,051 reads indicated from DBstats on the same database.

I used DASCRUBBER from the 09 of May 2017 and DAZZ_DB from 13th of January 2017.

Edited: I mixed up March and May, Scrubber recent DAZZ_DB not really

**Comment by thegenemyers** [comment]
Hi,

    I ran DB2fasta on several large scrubbed data sets I've produced 
locally here and did
not encounter the problem, so ...

    First thing is your versions seem old, the latest, and especially of 
the released Scrubber
are from late April.  So could you first reload, build, and use the 
latest version of DASCRUBBER
and DAZZ_DB and see if the problem persists?

    If it does then could you send me the output of "DBstats 
scrubbed_reads.db" and "cat scrubbed_reads.db".
Either the number of reads reported to be in the data base or the read 
indices for the block partition of
the data base have to be in error to give this problem and I'd like to 
confirm that is the case.  Then we
can go from there.

    -- Gene

**Comment by ebioman** [comment]
Thanks for the quick reply.
Indeed, I tried it again on a different data-set and did not experience any issues (DBSCRUBBER is up-to date DAZZ_DB I will have to update for the cluster).
In the former examples which generated the bug, the culprit seems to be one sequence (the last one)  which is empty in DB2fasta and has the following header:

    >m160221_234343_42182_c100960542550000001823211307011692_s1_p0/0/0_0

I will update the software and see whether this persists.

**Comment by thegenemyers** [comment]
Weird.  The 0/0_0 (well 0, pulses 0-0) is definitely bogus.  I would 
suspect that the problem
occurred when data was being imported *into* the database, so maybe look 
at the entry in the
input file corresponding to the location of the output shown (i.e. find 
the previous good read
output in the input, and then look at the next read in the input).
    -- Gene
