### ISSUE TITLE
creating a new or using the same DB for multiple SMRT cells

### ISSUE THREAD

**Issue by mictadlo** [thegenemyers/DAZZ_DB#29]
Hello,
I have got from RSII and Sequel in total around 100 SMRT cells from 1 organism. Do I have to create for each SMRT cell a new DB with fasta2DB in the following way:

```
fasta2DB DB1 SMRT1.fasta
fasta2DB DB2 SMRT2.fasta
fasta2DB DB3 SMRT3.fasta
```
or do I have to do it:
```
fasta2DB DB SMRT1.fasta
fasta2DB DB SMRT2.fasta
fasta2DB DB SMRT3.fasta
```

Thank you in advance.

Michal

**Comment by thegenemyers** [comment]
The second option, you want to add to the database, not create separate 
ones.
You could also say "fasta2DB DB SMRT*.fasta" which would build a DB from all
100 provided they are all in the current directory.
    -- Gene

**Comment by mictadlo** [comment]
Thank you
