### ISSUE TITLE
Forbidden usage of `exit` in `INTERACTIVE` mode

### ISSUE THREAD

**Issue by a-ludi** [thegenemyers/DAZZ_DB#43]
Hi Gene,

I am currently writing a wrapper library in D around `DB.c` among others. In this context it is important that the procedures in INTERACTIVE mode behave correctly. `Check_Track` in `DB.c` does not do that but writes to `stderr` and calls `exit(1)` on failure. Could you rewrite it to avoid that?

Just replacing with the `EXIT` and `EPRINTF(EPLACE, ...)` macros does not suffice because the procedure should *return* `>=0` in success (interactive) and *exit* `>0` on failure (non-interactive). For the time being, I will reimplement the procedure in my code and return `-3` on failure.

Please also update at least `DALIGNER` because that is the source for my "dazzler" C-library.

Best, Arne

**Comment by thegenemyers** [comment]
I went through all of DB.c and DB.h and found several additional places 
where the code had not been
modified for INTERACTIVE mode.  I also found a couple of places where 
files or memory were not
closed or freed, respectively, before error exiting (important in 
INTERACTIVE mode as these become
leaks).  All the changes were "mechanical" so just made sure it compiled 
and then checked the revised
code into all of the Dazzler modules including DALIGNER.
    Best,  Gene
