### ISSUE TITLE
Pacbio header line name inconsisten

### ISSUE THREAD

**Issue by homologus** [thegenemyers/DAZZ_DB#5]
Hi Gene,

I came across an error message, while doing fasta2DB and it originated from the following code block.

              if (strcmp(read+(rlen+1),prolog) != 0)
                { fprintf(stderr,"File %s.fasta, Line %d: Pacbio header line name inconsisten\n",
                                 core,nline);
                  goto error;
                }

Apparently it expects the pacbio IDs to be the same for all reads in a file. Any reason why I cannot mix PacBio reads from multiple sources?

**Comment by thegenemyers** [comment]
BTW, with the introduce of .dam's one can input to said .fasta's with different headers, but
it is not recommended for data reads, but rather smallish reference data sets.
