### ISSUE TITLE
Closing wrong file in Catrack when existing data file

### ISSUE THREAD

**Issue by cancan101** [thegenemyers/DAZZ_DB#6]
On [this line](https://github.com/thegenemyers/DAZZ_DB/blob/40136f82cbf13fccc264d0f7b34c87e2189e1609/Catrack.c#L114) you are calling `fclose` on `aout` when it should be `dout`:
```c
    dout = fopen(Catenate(prefix,argv[2],".","data"),"r");
    if (dout != NULL)
      { fprintf(stderr,"%s: Track file %s%s.data already exists!\n",Prog_Name,prefix,argv[2]);
        fclose(aout);
        exit (1);
      }
```

**Comment by thegenemyers** [comment]
Yes, thanks.  Will be in next minor update.  -- Gene

**Comment by thegenemyers** [comment]
Corrected in recent update.
