### ISSUE TITLE
Read too long

### ISSUE THREAD

**Issue by yasirs** [thegenemyers/DAZZ_DB#7]
I have some pacbio reads > 10kbases. When I run fasta2DB, I get 

    File filtered_subreads.fasta, Line 44: Fasta line is too long (> 9998 chars)

Is this the intended behavior ar am Idoing something wrong?

**Comment by yasirs** [comment]
Never mind, the lines ha to be wrapped.

**Comment by olechnwin** [comment]
@yasirs, I have the same message. Can you tell me how did you fix this? what did you mean by the lines has to be wrapped?

**Comment by thegenemyers** [comment]
The sequence should have new-lines in it so that each line of the file is not
too long.  Fastq files do not follow this convention and that may be the problem.
There are UNIX tools that will introduce the new-lines for you.
  -- Gene

**Comment by smm19900210** [comment]
Can you tell me how did you fix this?
