### ISSUE TITLE
Read FASTQ files

### ISSUE THREAD

**Issue by sjackman** [thegenemyers/DAZZ_DB#9]
Even if the quality values were ignored, it would be very helpful for fasta2DB to be able to read FASTQ files, to save converting FASTQ to FASTA.

**Comment by thegenemyers** [comment]
Hi,
   I hope you'll forgive me but I'm inclined not to do this for the simple reason that the q-values are bloody useless, so in my view, its a waste of time to have the machine generate .fastq to being with.  If you use my extraction tools in the DEXTRACT module you can just get the .fasta.
   Cheers, Gene
